export const BASE_URL = 'http://207.154.215.144:8080/api'; //

export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';

export const GET_CONVERTED_REQUEST = 'GET_CONVERTED_REQUEST';
export const GET_CONVERTED_SUCCESS = 'GET_CONVERTED_SUCCESS';
export const GET_CONVERTED_FAIL = 'GET_CONVERTED_FAIL';

export const GET_CURRENCIES_REQUEST = 'GET_CURRENCIES_REQUEST';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_FAIL = 'GET_CURRENCIES_FAIL';

export const SHOW_DROPDOWN = 'SHOW_DROPDOWN';
export const HIDE_DROPDOWN = 'HIDE_DROPDOWN';

export const SET_CURRENCY = 'SET_CURRENCY';

